[package]
name = "rholive"
version = "0.1.0"
edition = "2024"

[dependencies]
xcap = "0.1"
libpulse-simple-binding = "2.28"
tungstenite = "0.21"
tokio = { version = "1.37", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
egui = "0.27"
egui_window_glfw_passthrough = "0.3"
glow = "0.12"
